from words import Words

class Adjectives(Words):
    def __init__(self):
        self.words = [
            # 1 syllable
            'bad',
            'best',
            'big',
            'black',
            'blue',
            'clear',
            'close',
            'cold',
            'dark',
            'dead',
            'fine',
            'free',
            'full',
            'good',
            'great',
            'hard',
            'high',
            'hot',
            'late',
            'left',
            'long',
            'low',
            'new',
            'old',
            'past',
            'poor',
            'red',
            'right',
            'short',
            'small',
            'sure',
            'strong',
            'true',
            'young',
            'white',
            'whole',
            'wrong',

            # 2 syllables
            'able',
            'better',
            'certain',
            'central'
            'common',
            'current',
            'early',
            'easy',
            'entire',
            'foreign',
            'happy',
            'human',
            'large',
            'legal',
            'likely',
            'little',
            'local',
            'major',
            'only',
            'open',
            'other',
            'public',
            'ready',
            'real',
            'recent',
            'simple',
            'single',
            'social',
            'special',
        ]



