from words import Words        

class Nouns(Words):
    @classmethod
    def __init__(self):
        self.words = [
            # 1 syllable
            'book',
            'car',
            'case',
            'child',
            'day',
            'end',
            'eye',
            'fact',
            'friend',
            'game',
            'group',
            'hand',
            'head',
            'home',
            'hour',
            'house',
            'job',
            'kind',
            'law',
            'life',
            'line',
            'lot',
            'man',
            'month',
            'name',
            'night',
            'part',
            'place',
            'point',
            'right',
            'room',
            'school',
            'side',
            'state',
            'student',
            'team',
            'thing',
            'time',
            'year',
            'way',
            'week',
            'word',
            'world',
            'work',

            # 2 syllables
            'business',
            'city',
            'country',
            'father',
            'issue',
            'member',
            'minute',
            'money',
            'mother',
            'number',
            'people',
            'power',
            'problem',
            'program',
            'question',
            'service',
            'story',
            'study',
            'system',
            'water',
            'woman',
        ]

