from words import Words 

class RelativePronouns(Words):
    def __init__(self):
        self.words = [
            'up',
            'so',
            'out',
            'just',
            'now',
            'how',
            'then',
            'more',
            'also',
            'here',
            'well',
            'only',
            'very',
            'even',
            'very',
            'even',
            'back',
            'there',
            'down',
            'still',
            'in',
            'as',
            'too',
            'when',
            'never',
            'really',
            'most',
            'on',
            'why',
            'about',
            'over',
            'again',
            'where',
            'right',
            'off',
            'always',
            'today',
            'all',
            'far',
            'long',
            'away',
            'often',
            'yet',
            'ever',
        ]

