from words import Words

class Auxiliaries(Words):
    def __init__(self):
        self.words = [
            'is', # to be
            'does',
            'has',
            'can',
            'will',
            'should',
        ]


class Intransitives(Words):
    def __init__(self):
        self.words = [
            'be', # to be
            'is', # to be
            'does',
            'says',
            'goes',
            'makes',
            'knows',
            'wills',
            'thinks',
            'comes',
            'looks',
            'gives',
            'works',
            'calls',
            'tries',
            'asks',
            'needs',
            'feels',
            'puts',
            'means',
            'keeps',
            'begins',
            'seems',
            'talks',
            'starts',
            'might',
            'shows',
            'runs',
            'moves',
            'lives',
            'happens',
            'must',
            'writes',
            'sits',
            'stands',
            'loses',
            'continues',
            'learns',
            'leads',
            'speaks',
            'allows',
        ]

class Transitives(Words):
    def __init__(self):
        self.words = [
            'be',
            'is',
            'have',
            'do',
            'say',
            'go',
            'get',
            'make',
            'know',
            'think',
            'take',
            'see',
            'want',
            'look',
            'use',
            'find',
            'tell',
            'work',
            'call',
            'need',
            'become',
            'leave',
            'keep',
            'let',
            'help',
            'turn',
            'start',
            'show',
            'hear',
            'play',
            'run',
            'move',
            'like',
            'believe',
            'hold',
            'bring',
            'must',
            'write',
            'provide',
            'lose',
            'pay',
            'meet',
            'include',
            'set',
            'learn',
            'change',
            'lead',
            'understand',
            'watch',
            'follow',
            'stop',
            'create',
            'read',
            'add',
        ]

